/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransitionRouteImport } from './routes/transition'
import { Route as ResultRouteImport } from './routes/result'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as CompletionRouteImport } from './routes/completion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstructionSessionRouteImport } from './routes/instruction.$session'
import { Route as AssessmentSessionRouteImport } from './routes/assessment.$session'

const TransitionRoute = TransitionRouteImport.update({
  id: '/transition',
  path: '/transition',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletionRoute = CompletionRouteImport.update({
  id: '/completion',
  path: '/completion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionSessionRoute = InstructionSessionRouteImport.update({
  id: '/instruction/$session',
  path: '/instruction/$session',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentSessionRoute = AssessmentSessionRouteImport.update({
  id: '/assessment/$session',
  path: '/assessment/$session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completion': typeof CompletionRoute
  '/identity': typeof IdentityRoute
  '/result': typeof ResultRoute
  '/transition': typeof TransitionRoute
  '/assessment/$session': typeof AssessmentSessionRoute
  '/instruction/$session': typeof InstructionSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completion': typeof CompletionRoute
  '/identity': typeof IdentityRoute
  '/result': typeof ResultRoute
  '/transition': typeof TransitionRoute
  '/assessment/$session': typeof AssessmentSessionRoute
  '/instruction/$session': typeof InstructionSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completion': typeof CompletionRoute
  '/identity': typeof IdentityRoute
  '/result': typeof ResultRoute
  '/transition': typeof TransitionRoute
  '/assessment/$session': typeof AssessmentSessionRoute
  '/instruction/$session': typeof InstructionSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completion'
    | '/identity'
    | '/result'
    | '/transition'
    | '/assessment/$session'
    | '/instruction/$session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/completion'
    | '/identity'
    | '/result'
    | '/transition'
    | '/assessment/$session'
    | '/instruction/$session'
  id:
    | '__root__'
    | '/'
    | '/completion'
    | '/identity'
    | '/result'
    | '/transition'
    | '/assessment/$session'
    | '/instruction/$session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletionRoute: typeof CompletionRoute
  IdentityRoute: typeof IdentityRoute
  ResultRoute: typeof ResultRoute
  TransitionRoute: typeof TransitionRoute
  AssessmentSessionRoute: typeof AssessmentSessionRoute
  InstructionSessionRoute: typeof InstructionSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transition': {
      id: '/transition'
      path: '/transition'
      fullPath: '/transition'
      preLoaderRoute: typeof TransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completion': {
      id: '/completion'
      path: '/completion'
      fullPath: '/completion'
      preLoaderRoute: typeof CompletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruction/$session': {
      id: '/instruction/$session'
      path: '/instruction/$session'
      fullPath: '/instruction/$session'
      preLoaderRoute: typeof InstructionSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$session': {
      id: '/assessment/$session'
      path: '/assessment/$session'
      fullPath: '/assessment/$session'
      preLoaderRoute: typeof AssessmentSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletionRoute: CompletionRoute,
  IdentityRoute: IdentityRoute,
  ResultRoute: ResultRoute,
  TransitionRoute: TransitionRoute,
  AssessmentSessionRoute: AssessmentSessionRoute,
  InstructionSessionRoute: InstructionSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
